name: RandomCrate
main: com.faceyspacies.RandomCrate.RandomCrate
version: 1.1.0
author: tehTyA

commands:
   crate:
      description: gives [player] a Mystery Crate. If player isn't specified, command user gets one. If amount isn't provided, they get 1. 
      usage: /crate give [player] [amount of crates]
      permission: RandomCrate.crate
      permission-message: ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("random-crates-no-permission"))
      
permissions:
   RandomCrate.crate:
      description: Allows one to give out Mystery Crates
      default: op
